(()=>{
'use strict';
const $=s=>document.querySelector(s); const app=$('#app');
const KEY='bookingDiaryBookingsV2', SETTINGS='bookingDiarySettingsV2';
let bookings=JSON.parse(localStorage.getItem(KEY)||'[]');
let settings=JSON.parse(localStorage.getItem(SETTINGS)||'{"defaultReminderDays":2,"defaultReminderTime":"09:00"}');
let tab='home', selectedId=null, editingId=null, filter='all', query='', calDate=new Date(), calSelected=null, installPrompt=null;
const eventTypes=['Bridal','Engagement','Wedding','Reception','Party','Other'];
const paymentStatuses=['Advance Paid','Part Paid','Fully Paid','Pending'];
const bookingStatuses=['Confirmed','Tentative','Completed','Cancelled'];
const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const money=n=>'₹'+Number(n||0).toLocaleString('en-IN');
const diff=date=>{const [y,m,d]=date.split('-').map(Number), a=new Date(y,m-1,d), t=new Date(); t.setHours(0,0,0,0); return Math.round((a-t)/86400000)};
const label=date=>new Date(date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'});
const when=date=>{const n=diff(date);return n===0?'Today':n===1?'Tomorrow':n===2?'In 2 days':n>2?`In ${n} days`:`${Math.abs(n)} days ago`};
const save=()=>localStorage.setItem(KEY,JSON.stringify(bookings));
const saveSettings=()=>localStorage.setItem(SETTINGS,JSON.stringify(settings));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));
const phone=p=>{let x=String(p||'').replace(/\D/g,'');if(x.length===10)x='91'+x;return x};
const toast=t=>{const x=document.createElement('div');x.className='toast';x.textContent=t;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)};
const notifyDue=()=>{if(!('Notification' in window)||Notification.permission!=='granted')return;const seen=JSON.parse(localStorage.getItem('bookingDiaryNotified')||'{}');let changed=false;bookings.filter(b=>b.reminderEnabled!==false&&b.bookingStatus!=='Cancelled'&&b.bookingStatus!=='Completed').forEach(b=>{const d=diff(b.eventDate), r=Number(b.reminderDays??2), key=`${b.id}-${b.eventDate}-${r}`;if(d===r&&!seen[key]){new Notification('Booking Reminder',{body:`${b.clientName}'s ${b.eventType} booking is in ${r} day${r===1?'':'s'} — ${label(b.eventDate)}, ${b.location||b.city||''}`});seen[key]=Date.now();changed=true}});if(changed)localStorage.setItem('bookingDiaryNotified',JSON.stringify(seen))};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;render()});
if('serviceWorker' in navigator && location.protocol!=='file:') navigator.serviceWorker.register('sw.js').catch(()=>{});
setInterval(notifyDue,60000); setTimeout(notifyDue,1200);
function shell(content){return `<div class="shell"><main>${content}</main>${tab!=='form'&&tab!=='detail'?nav():''}</div>`}
function nav(){return `<nav class="bottom"><button data-tab="home" class="${tab==='home'?'active':''}">⌂<span>Home</span></button><button data-tab="calendar" class="${tab==='calendar'?'active':''}">▦<span>Calendar</span></button><button id="add" class="add">＋</button><button data-tab="reminders" class="${tab==='reminders'?'active':''}">♧<span>Reminders</span></button><button data-tab="settings" class="${tab==='settings'?'active':''}">⚙<span>Settings</span></button></nav>`}
function card(b){const urgent=diff(b.eventDate)===2?'urgent':'';return `<button class="card ${urgent}" data-open="${b.id}"><div class="cardhead"><div><span class="pill">${esc(b.eventType)}</span><h3>${esc(b.clientName)}</h3></div><div class="date"><b>${label(b.eventDate)}</b><em>${when(b.eventDate)}</em></div></div><div class="meta">☎ ${esc(b.mobile||'—')}</div><div class="meta">⌖ ${esc([b.location,b.city].filter(Boolean).join(', ')||'—')}</div><div class="money"><span>Advance ${money(b.advance)}</span><span>Total ${money(b.total)}</span><span>Balance ${money(b.balance)}</span></div><div class="status">${esc(b.bookingStatus)} · ${esc(b.paymentStatus)}</div></button>`}
function home(){const up=[...bookings].filter(b=>diff(b.eventDate)>=0&&b.bookingStatus!=='Cancelled').sort((a,b)=>a.eventDate.localeCompare(b.eventDate));const counts={today:up.filter(b=>diff(b.eventDate)===0).length,tom:up.filter(b=>diff(b.eventDate)===1).length,two:up.filter(b=>diff(b.eventDate)===2).length,week:up.filter(b=>diff(b.eventDate)>=0&&diff(b.eventDate)<=7).length};let data=up.filter(b=>`${b.clientName} ${b.mobile} ${b.location} ${b.city} ${b.eventType}`.toLowerCase().includes(query.toLowerCase()));if(filter==='2days')data=data.filter(b=>diff(b.eventDate)===2);if(filter==='pending')data=data.filter(b=>Number(b.balance)>0);if(filter==='Confirmed')data=data.filter(b=>b.bookingStatus==='Confirmed');return `<div class="page"><header class="hero"><div><div class="eyebrow">Private Booking Manager</div><h1>Booking Diary</h1><p>Every booking, payment and reminder in one place.</p></div><button id="quickAdd" class="btn primary">＋ Add Booking</button></header><div class="stats"><div class="stat"><strong>${counts.today}</strong><span>Today</span></div><div class="stat"><strong>${counts.tom}</strong><span>Tomorrow</span></div><div class="stat ${counts.two?'hot':''}"><strong>${counts.two}</strong><span>In 2 Days</span></div><div class="stat"><strong>${counts.week}</strong><span>This Week</span></div></div><div class="search">⌕ <input id="search" placeholder="Search name, phone, location..." value="${esc(query)}"></div><div class="chips">${[['all','All'],['2days','In 2 Days'],['pending','Payment Pending'],['Confirmed','Confirmed']].map(([v,l])=>`<button class="chip ${filter===v?'active':''}" data-filter="${v}">${l}</button>`).join('')}</div><div class="listhead"><h2>Upcoming Bookings</h2><span>${data.length}</span></div><div class="list">${data.length?data.map(card).join(''):'<div class="empty"><h3>No upcoming bookings</h3><p>Tap Add Booking to save your first booking.</p></div>'}</div></div>`}
function form(){const b=bookings.find(x=>x.id===editingId)||{};const v=(k,d='')=>esc(b[k]??d);return `<div class="page"><div class="topbar"><button id="back" class="icon">‹</button><div><div class="eyebrow">${editingId?'Edit':'New'} Booking</div><h1>${editingId?'Update Booking':'Add Booking'}</h1></div><div></div></div><form id="bookingForm" class="form"><div class="sectiontitle">Essential Details</div><div class="grid"><label class="label">Event Date<input required type="date" name="eventDate" value="${v('eventDate',todayISO())}"></label><label class="label">Event Type<select name="eventType">${eventTypes.map(x=>`<option ${v('eventType','Bridal')===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="label">Client Name<input required name="clientName" value="${v('clientName')}"></label><label class="label">Mobile Number<input required inputmode="tel" name="mobile" value="${v('mobile')}"></label><label class="label wide">Location / Venue<input name="location" value="${v('location')}"></label><label class="label">City<input name="city" value="${v('city')}"></label><label class="label">Alternate Mobile<input inputmode="tel" name="alternateMobile" value="${v('alternateMobile')}"></label></div><div class="sectiontitle">Payment</div><div class="grid"><label class="label">Advance<input type="number" min="0" name="advance" value="${v('advance',0)}"></label><label class="label">Final Amount<input type="number" min="0" name="total" value="${v('total',0)}"></label><label class="label">Balance<input readonly name="balance" value="${v('balance',0)}"></label><label class="label">Payment Status<select name="paymentStatus">${paymentStatuses.map(x=>`<option ${v('paymentStatus','Advance Paid')===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="label">Booking Status<select name="bookingStatus">${bookingStatuses.map(x=>`<option ${v('bookingStatus','Confirmed')===x?'selected':''}>${x}</option>`).join('')}</select></label></div><div class="sectiontitle">Reminder & Notes</div><div class="switch"><span>🔔 Reminder enabled</span><input type="checkbox" name="reminderEnabled" ${b.reminderEnabled===false?'':'checked'}></div><div class="grid"><label class="label">Remind Before<select name="reminderDays">${[1,2,3,7].map(x=>`<option value="${x}" ${Number(b.reminderDays??settings.defaultReminderDays)===x?'selected':''}>${x} day${x===1?'':'s'}</option>`).join('')}</select></label><label class="label">Reminder Time<input type="time" name="reminderTime" value="${v('reminderTime',settings.defaultReminderTime)}"></label><label class="label wide">Notes / Special Instructions<textarea name="notes" rows="4">${v('notes')}</textarea></label></div><button class="btn primary" type="submit">Save Booking</button></form></div>`}
function detail(){const b=bookings.find(x=>x.id===selectedId);if(!b){tab='home';return home()}const place=[b.location,b.city].filter(Boolean).join(', ');return `<div class="page"><div class="topbar"><button id="back" class="icon">‹</button><div><div class="eyebrow">${esc(b.eventType)}</div><h1>${esc(b.clientName)}</h1></div><button id="edit" class="icon">✎</button></div><div class="detaildate"><strong>${label(b.eventDate)}</strong><span>${esc(b.bookingStatus)}</span></div><div class="actions"><a href="tel:${esc(b.mobile)}">☎ Call</a><a target="_blank" rel="noreferrer" href="https://wa.me/${phone(b.mobile)}">◉ WhatsApp</a><button id="copyPlace">⌖ Copy Location</button></div><div class="panel"><h3>Booking</h3>${row('Event',b.eventType)}${row('Date',label(b.eventDate))}${row('Mobile',b.mobile)}${row('Alternate',b.alternateMobile||'—')}${row('Location',place||'—')}</div><div class="panel"><h3>Payment</h3>${row('Advance',money(b.advance))}${row('Total',money(b.total))}${row('Balance',money(b.balance),true)}${row('Payment Status',b.paymentStatus)}</div><div class="panel"><h3>Reminder & Notes</h3>${row('Reminder',b.reminderEnabled===false?'Off':`${b.reminderDays??2} days before at ${b.reminderTime||'09:00'}`)}<p class="notes">${esc(b.notes||'No notes added.')}</p></div><div class="stack"><button id="calendarReminder" class="btn primary">＋ Add 2-Day Phone Calendar Reminder</button><button id="complete" class="btn secondary">✓ Mark Completed</button><button id="paid" class="btn secondary">₹ Mark Fully Paid</button><button id="delete" class="btn danger">Delete Booking</button></div></div>`}
function row(a,b,ac=false){return `<div class="row"><span>${esc(a)}</span><b class="${ac?'accent':''}">${esc(b)}</b></div>`}
function reminders(){const modes=[['2','In 2 Days'],['today','Today'],['pending','Payment Pending'],['up','Upcoming']];let mode=filter; if(!['2','today','pending','up'].includes(mode))mode='2';let data=bookings.filter(b=>b.bookingStatus!=='Cancelled'&&b.bookingStatus!=='Completed');if(mode==='2')data=data.filter(b=>diff(b.eventDate)===2);if(mode==='today')data=data.filter(b=>diff(b.eventDate)===0);if(mode==='pending')data=data.filter(b=>Number(b.balance)>0);if(mode==='up')data=data.filter(b=>diff(b.eventDate)>=0);data.sort((a,b)=>a.eventDate.localeCompare(b.eventDate));return `<div class="page"><div class="simple"><div class="eyebrow">Reminder Center</div><h1>Reminders</h1><p>Bookings that need your attention.</p></div><div class="chips">${modes.map(([v,l])=>`<button class="chip ${mode===v?'active':''}" data-rmode="${v}">${l}</button>`).join('')}</div><div class="list">${data.length?data.map(card).join(''):'<div class="empty">Nothing pending here.</div>'}</div></div>`}
function calendar(){const y=calDate.getFullYear(),m=calDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=first.getDay();let cells='';for(let i=0;i<start;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,count=bookings.filter(b=>b.eventDate===iso&&b.bookingStatus!=='Cancelled').length;cells+=`<button data-day="${iso}" class="${calSelected===iso?'selected':''}">${d}${count?`<i>${count}</i>`:''}</button>`}const dayBookings=calSelected?bookings.filter(b=>b.eventDate===calSelected):[];return `<div class="page"><div class="simple"><div class="eyebrow">Monthly View</div><h1>Calendar</h1></div><div class="calendarhead"><button id="prev" class="icon">‹</button><b>${calDate.toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</b><button id="next" class="icon">›</button></div><div class="week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="cal">${cells}</div>${calSelected?`<div class="listhead"><h2>${label(calSelected)}</h2><span>${dayBookings.length}</span></div><div class="list">${dayBookings.map(card).join('')||'<div class="empty">No bookings</div>'}</div>`:''}</div>`}
function settingsPage(){const perm=('Notification' in window)?Notification.permission:'unsupported';return `<div class="page"><div class="simple"><div class="eyebrow">App Settings</div><h1>Settings</h1><p>Install, reminders and backup.</p></div><div class="installbox"><h3>Install on this phone</h3><p class="muted">Android: Chrome → Install App. iPhone: Safari → Share → Add to Home Screen.</p>${installPrompt?'<button id="install" class="btn primary small">Install App</button>':''}</div><div class="panel"><h3>Notifications</h3><p class="muted">Permission: <b>${perm}</b>. The app highlights reminders whenever opened. For a reliable alert when the app is closed on both Android and iPhone, use “Add 2-Day Phone Calendar Reminder” inside each booking.</p><button id="notify" class="btn secondary small">Enable Notifications</button></div><div class="panel"><h3>Default Reminder</h3><div class="grid"><label class="label">Days Before<select id="defaultDays">${[1,2,3,7].map(x=>`<option value="${x}" ${Number(settings.defaultReminderDays)===x?'selected':''}>${x}</option>`).join('')}</select></label><label class="label">Time<input id="defaultTime" type="time" value="${esc(settings.defaultReminderTime)}"></label></div></div><div class="panel"><h3>Backup</h3><p class="muted">Export all booking details as CSV.</p><button id="export" class="btn secondary small">⇩ Export CSV</button></div><div class="panel"><h3>Data</h3><p class="muted">Bookings are stored privately on this device/browser. Keep CSV backups if the data is important.</p></div></div>`}
function render(){let content=tab==='home'?home():tab==='form'?form():tab==='detail'?detail():tab==='reminders'?reminders():tab==='calendar'?calendar():settingsPage();app.innerHTML=shell(content);bind()}
function bind(){document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;filter='all';render()});$('#add')&&($('#add').onclick=()=>{editingId=null;tab='form';render()});$('#quickAdd')&&($('#quickAdd').onclick=()=>{editingId=null;tab='form';render()});$('#back')&&($('#back').onclick=()=>{tab=selectedId?'detail':'home';if(tab==='detail'&&!bookings.find(x=>x.id===selectedId))tab='home';render()});document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>{selectedId=x.dataset.open;tab='detail';render()});$('#search')&&($('#search').oninput=e=>{query=e.target.value;const pos=e.target.selectionStart;render();setTimeout(()=>{const s=$('#search');if(s){s.focus();s.setSelectionRange(pos,pos)}},0)});document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;render()});document.querySelectorAll('[data-rmode]').forEach(x=>x.onclick=()=>{filter=x.dataset.rmode;render()});
const f=$('#bookingForm');if(f){const calc=()=>{const a=Number(f.advance.value||0),t=Number(f.total.value||0);f.balance.value=Math.max(0,t-a)};f.advance.oninput=calc;f.total.oninput=calc;f.onsubmit=e=>{e.preventDefault();const fd=new FormData(f),obj=Object.fromEntries(fd.entries());obj.advance=Number(obj.advance||0);obj.total=Number(obj.total||0);obj.balance=Math.max(0,obj.total-obj.advance);obj.reminderDays=Number(obj.reminderDays||2);obj.reminderEnabled=f.reminderEnabled.checked;const now=new Date().toISOString();if(editingId){const i=bookings.findIndex(x=>x.id===editingId);obj.id=editingId;obj.createdAt=bookings[i].createdAt;obj.updatedAt=now;bookings[i]=obj}else{obj.id=Date.now().toString(36)+Math.random().toString(36).slice(2);obj.createdAt=now;obj.updatedAt=now;bookings.push(obj)}save();selectedId=obj.id;editingId=null;tab='detail';toast('Booking saved');render();notifyDue()}}
$('#edit')&&($('#edit').onclick=()=>{editingId=selectedId;tab='form';render()});$('#delete')&&($('#delete').onclick=()=>{const b=bookings.find(x=>x.id===selectedId);if(confirm(`Delete ${b.clientName}'s booking?`)){bookings=bookings.filter(x=>x.id!==selectedId);save();selectedId=null;tab='home';render()}});$('#complete')&&($('#complete').onclick=()=>updateSelected({bookingStatus:'Completed'}));$('#paid')&&($('#paid').onclick=()=>{const b=bookings.find(x=>x.id===selectedId);updateSelected({paymentStatus:'Fully Paid',advance:b.total,balance:0})});$('#copyPlace')&&($('#copyPlace').onclick=async()=>{const b=bookings.find(x=>x.id===selectedId);await navigator.clipboard?.writeText([b.location,b.city].filter(Boolean).join(', '));toast('Location copied')});$('#calendarReminder')&&($('#calendarReminder').onclick=()=>downloadICS(bookings.find(x=>x.id===selectedId)));
$('#prev')&&($('#prev').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()-1,1);render()});$('#next')&&($('#next').onclick=()=>{calDate=new Date(calDate.getFullYear(),calDate.getMonth()+1,1);render()});document.querySelectorAll('[data-day]').forEach(x=>x.onclick=()=>{calSelected=x.dataset.day;render()});
$('#notify')&&($('#notify').onclick=async()=>{if(!('Notification' in window))return toast('Notifications not supported here');const p=await Notification.requestPermission();toast(`Notifications: ${p}`);render();notifyDue()});$('#install')&&($('#install').onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;render()}});$('#defaultDays')&&($('#defaultDays').onchange=e=>{settings.defaultReminderDays=Number(e.target.value);saveSettings()});$('#defaultTime')&&($('#defaultTime').onchange=e=>{settings.defaultReminderTime=e.target.value;saveSettings()});$('#export')&&($('#export').onclick=exportCSV)}
function updateSelected(ch){const i=bookings.findIndex(x=>x.id===selectedId);bookings[i]={...bookings[i],...ch,updatedAt:new Date().toISOString()};save();toast('Updated');render()}
function exportCSV(){const cols=['Event Date','Event Type','Client Name','Mobile','Alternate Mobile','Location','City','Advance','Total','Balance','Payment Status','Booking Status','Reminder Days','Reminder Time','Notes'];const val=(b,k)=>({'Event Date':b.eventDate,'Event Type':b.eventType,'Client Name':b.clientName,'Mobile':b.mobile,'Alternate Mobile':b.alternateMobile,'Location':b.location,'City':b.city,'Advance':b.advance,'Total':b.total,'Balance':b.balance,'Payment Status':b.paymentStatus,'Booking Status':b.bookingStatus,'Reminder Days':b.reminderDays,'Reminder Time':b.reminderTime,'Notes':b.notes}[k]??'');const csv=[cols.join(','),...bookings.map(b=>cols.map(k=>'"'+String(val(b,k)).replace(/"/g,'""')+'"').join(','))].join('\n');download(new Blob([csv],{type:'text/csv'}),`booking-diary-${todayISO()}.csv`)}
function downloadICS(b){const dt=b.eventDate.replaceAll('-','');const clean=s=>String(s||'').replace(/[\\;,\n]/g,m=>({'\\':'\\\\',';':'\\;',',':'\\,','\n':'\\n'}[m]));const place=[b.location,b.city].filter(Boolean).join(', ');const desc=`Client: ${b.clientName}\\nMobile: ${b.mobile}\\nAdvance: ${money(b.advance)}\\nTotal: ${money(b.total)}\\nBalance: ${money(b.balance)}\\nNotes: ${b.notes||''}`;const ics=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Booking Diary//EN\r\nBEGIN:VEVENT\r\nUID:${b.id}@bookingdiary\r\nDTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}\r\nDTSTART;VALUE=DATE:${dt}\r\nDTEND;VALUE=DATE:${dt}\r\nSUMMARY:${clean(`${b.clientName} - ${b.eventType}`)}\r\nLOCATION:${clean(place)}\r\nDESCRIPTION:${clean(desc)}\r\nBEGIN:VALARM\r\nTRIGGER:-P2D\r\nACTION:DISPLAY\r\nDESCRIPTION:Booking in 2 days: ${clean(`${b.clientName} - ${b.eventType}`)}\r\nEND:VALARM\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`;download(new Blob([ics],{type:'text/calendar;charset=utf-8'}),`${b.clientName.replace(/[^a-z0-9]/gi,'-')}-booking.ics`);toast('Calendar reminder file ready')}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
render();
})();
